opentargets/platform-etl-backend

- .gitignore
- buid.sbt
- elasticsearch/index_settings_search.json
- platformDataBackend.sc
- platformDataBackendAssociationsOTF.sc
- platformDataBackendSearch.sc
It generates one index per entity. Currently: drugs, targets and diseases
> search pipeline implementation (first phase)

- README.md
- elasticsearch/load_search.sh
- elasticsearch/load_targets.sh
> Fixing typo

- platformDataBackendDisease.sc
The disease index contains the main info about the disease.
Moreover, it contains parentIds, ancestors, decedents.
> Disease index 1.0

- .gitignore
- README.md
- backend/common.sc
- backend/disease.sc
- backend/drug.sc
- backend/target.sc
- buid.sbt
- platformETL.sc
- project/Dependencies.scala
- resources/amm.application.conf.example
Script able to build the disease, target and drug indexes using the config file under resources/amm.application.conf
Mainly
-- Use modules 
-- Spark common functions
-- Reusable code
> Unique script with modules and parameters

- .scalafmt.conf
- README.md
- hooks/pre-commit.scalafmt
Adding scalafmt and git hooks 
To avoid scalafmt just type --no-verify 
git commit -m "your commit message here" --no-verify
> Added scalafmt and git hooks

- backend/cancerBiomarkers.sc
- elasticsearch/load_cancerbiomarker.sh
- platformETL.sc
This script generates the info about cancerBiomarkers for the target
> CancerBiomarkers for target

- backend/cancerBiomarkers.sc
- elasticsearch/load_cancerbiomarker.sh
Cancermarker index.
This index implements the relationship (Biomarker, Target, Disease, Drug )
> Cm biomarkers entity

- backend/common.sc
- backend/dataDrivenRelation.sc
- platformETL.sc
- resources/application.conf
This script creates targetRelation and diseaseRelation indices.
> Cm ddr index

- backend/common.sc
During the merge, we forgot to add rea and eco input options
> Adding option rea and eco

- backend/associations.sc
- backend/associationsLLR.sc
- backend/cancerBiomarkers.sc
- backend/clinicalTrials.sc
- backend/common.sc
- backend/dataDrivenRelation.sc
- backend/disease.sc
- backend/drug.sc
- backend/eco.sc
- backend/evidenceDrug.sc
- backend/evidenceProteinFix.sc
- backend/reactome.sc
- backend/search.sc
- backend/target.sc
- resources/application.conf
This is the first refactoring in order to read any types of files.
Eg. parquet files.
Parquet files are faster and smaller respect json files.
Changed: application.conf and most of the files that use common package.
> Read any types of input files. Eg. parquet/json

- elasticsearch/load_disease_relation.sh
- elasticsearch/load_drugs.sh
- elasticsearch/load_ev_drug.sh
- elasticsearch/load_target_relation.sh
Fixed a couple of scripts and add target_relation and disease_relation scripts
> Loading scripts

- backend/target.sc
#922
More info https://app.zenhub.com/workspaces/platform-primary-58a421fd8c85e652659a1486/issues/opentargets/platform/922
> Fix 922 issue: tractability info

- backend/target.sc
Fixing issue #912
https://app.zenhub.com/workspaces/platform-primary-58a421fd8c85e652659a1486/issues/opentargets/platform/912
> Fixed evidence value

- backend/target.sc
[Ticket 923](https://app.zenhub.com/workspaces/platform-primary-58a421fd8c85e652659a1486/issues/opentargets/platform/923)
> Fixing safety data

- backend/common.sc
- backend/target.sc
[Ticket 280](https://app.zenhub.com/workspaces/platform-primary-58a421fd8c85e652659a1486/issues/opentargets/platform/280)
> added reatome and keys without spaces

- backend/target.sc
Change pmid from String to Long for all hallmarks struct
> hallmark pmid fix

- backend/evidenceDrugDirect.sc
- elasticsearch/load_evidence_direct.sh
- platformETL.sc
Example here: 20.02_evidence_direct/_search
This index has Drug, Disesase, Target and CT.
> Cm direct evidence drug

- backend/target.sc
Fixing issue with go structure
> fix struct go

- backend/dataDrivenRelation.sc
- backend/target.sc
Added info for safety(experimental_toxicity) and tractability (other_modalities).
Fixed data relational data typo (countAndB to countAAndB)
More details about these modifications here:
[943](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/943)
[945](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/945)
> New safety and tractability info

- elasticsearch/load_all.sh
- elasticsearch/load_cancerbiomarker.sh
- elasticsearch/load_disease_relation.sh
- elasticsearch/load_diseases.sh
- elasticsearch/load_drugs.sh
- elasticsearch/load_eco.sh
- elasticsearch/load_ev_drug.sh
- elasticsearch/load_evidence_direct.sh
- elasticsearch/load_jsons.sh
- elasticsearch/load_openfda_faers.sh
- elasticsearch/load_reactome.sh
- elasticsearch/load_target_relation.sh
- elasticsearch/load_targets.sh
RELEASE as env variable and added load_all.sh
> Cm elasticsearch release prefix

- backend/disease.sc
Removed phenotype count.
Phenototype is not present when the data are not available.
> Removed phenotype count

- .gitignore
- README.md
- buid.sbt
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- src/main/resources/application.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Associations.scala
- src/main/scala/io/opentargets/etl/backend/AssociationsLLR.scala
- src/main/scala/io/opentargets/etl/backend/CancerBiomarkers.scala
- src/main/scala/io/opentargets/etl/backend/ClinicalTrials.scala
- src/main/scala/io/opentargets/etl/backend/Common.scala
- src/main/scala/io/opentargets/etl/backend/Dailymed.scala
- src/main/scala/io/opentargets/etl/backend/DataDrivenRelation.scala
- src/main/scala/io/opentargets/etl/backend/Disease.scala
- src/main/scala/io/opentargets/etl/backend/Drug.scala
- src/main/scala/io/opentargets/etl/backend/Eco.scala
- src/main/scala/io/opentargets/etl/backend/EvidenceDrug.scala
- src/main/scala/io/opentargets/etl/backend/EvidenceDrugDirect.scala
- src/main/scala/io/opentargets/etl/backend/EvidenceProteinFix.scala
- src/main/scala/io/opentargets/etl/backend/Reactome.scala
- src/main/scala/io/opentargets/etl/backend/Search.scala
- src/main/scala/io/opentargets/etl/backend/Target.scala
> Create Fat JAR

- README.md
- application.conf
- deprecated/backend/target.sc
- elasticsearch/load_all.sh
- elasticsearch/load_cancerbiomarker.sh
- elasticsearch/load_disease_relation.sh
- elasticsearch/load_diseases.sh
- elasticsearch/load_drugs.sh
- elasticsearch/load_eco.sh
- elasticsearch/load_ev_drug.sh
- elasticsearch/load_evidence_direct.sh
- elasticsearch/load_expression.sh
- elasticsearch/load_jsons.sh
- elasticsearch/load_jsons_search.sh
- elasticsearch/load_openfda_faers.sh
- elasticsearch/load_reactome.sh
- elasticsearch/load_search.sh
- elasticsearch/load_target_relation.sh
- elasticsearch/load_targets.sh
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/EvidenceDrugDirect.scala
- src/main/scala/io/opentargets/etl/backend/Expression.scala
- src/main/scala/io/opentargets/etl/backend/MousePhenotypes.scala
- src/main/scala/io/opentargets/etl/backend/Target.scala
Mousephenotype, expression, tep included
Removed ortholog
Added the load by gs storage
> Added TEP, mousephenotypes and loading ES using GS

- src/main/scala/io/opentargets/etl/backend/Disease.scala
Refactor the code following @mkarmona hints
> refactoring static files output

- README.md
- elasticsearch/load_all.sh
- elasticsearch/load_drugBeta.sh
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/drug_beta/MechanismOfAction.scala
1. Adding script to load the outputs into an ElasticSearch index
2. Adding to readme with more specific instructions on loading outputs into ES
3. Fixing errors identified on integrating with API - small name changes and a merge fail whereby 'targets' weren't being included in the MechanismOfAction. 
Note: Branch can be deleted after merging
> Drug beta es integration

- src/main/scala/io/opentargets/etl/backend/Interactions.scala
String resource provides the score in a different way. 
Change the code to transform the field in a proper way.
Eg. 900 -> 0.9
Fixed
*) HGNC code mapping
*) trim the code
> Fix score for string

- src/main/scala/io/opentargets/etl/backend/Interactions.scala
Added a new mapping for interaction
> Added new mapping using Gene_Name

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/DrugBeta.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/DrugExtensions.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/Indication.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/Molecule.scala
- src/main/scala/io/opentargets/etl/backend/spark/Helpers.scala
- src/test/scala/io/opentargets/etl/backend/DrugBeta/DrugExtensionsTest.scala
- src/test/scala/io/opentargets/etl/backend/DrugBeta/MoleculeTest.scala
- src/test/scala/io/opentargets/etl/backend/MoleculeTest.scala
Adding a mechanism to easily extend the content of the 'synonym' field. This method can be pretty easily extended to other fields, so long as we can uniquely identify the records.
> Drug extension mechanism

- README.md
- src/main/scala/io/opentargets/etl/backend/drug_beta/DrugBeta.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/Molecule.scala
- src/test/scala/io/opentargets/etl/backend/DrugBeta/MoleculeTest.scala
- Updating definition of drug (new definition outlined in readme, and see "platform backend - drugs" document for discussion)
- Fixes bug where cross references weren't properly collated
> Updating with new definition of drug

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/DrugBeta.scala
- src/test/scala/io/opentargets/etl/ConfigurationTest.scala
Separating all of the configuration necessary for the drug-beta step into it's own section of the configuration file.
> refactoring drug-beta config

- src/main/scala/io/opentargets/etl/backend/drug_beta/DrugBeta.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/Indication.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/MechanismOfAction.scala
- src/main/scala/io/opentargets/etl/backend/drug_beta/Molecule.scala
- src/test/scala/io/opentargets/etl/backend/DrugBeta/IndicationTest.scala
Adding some new fields and cleaning up.
> Add approved drug fields

- src/main/scala/io/opentargets/etl/backend/Interactions.scala
Add speciesA and species B to interaction
> Cm interaction species

- src/main/resources/reference.conf
Added `diseaseFromSource` and `allelicRequirements` to the unique association fields of `clingen`
> Update ClinGen UAFs

- src/main/scala/io/opentargets/etl/backend/Search.scala
Disease.synonyms changed structure.
Adapt the code to the new structure
> Transform synonyms struct / array

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Search.scala
Using flattenCat as suggested by @mkarmona
> synonyms solution using flattenCat

- README.md
> Update section dataproc

- src/main/scala/io/opentargets/etl/backend/CancerBiomarkers.scala
Fixed the issue with Cancerbiomarked using dataproc service
> fixed cancerbiomarker issue

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/Search.scala
Fixed search step:
*) Disease phenotype and synonyms
*) Drug mechanism
> Cm fix phenotype search

- elasticsearch/load_all.sh
- elasticsearch/load_interaction_evidence.sh
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/Interactions.scala
> refact input for interactions

- .gitignore
- elasticsearch/load_drugs.sh
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/drug/Drug.scala
- src/main/scala/io/opentargets/etl/backend/drug/DrugWarning.scala
- src/test/scala/io/opentargets/etl/backend/Drug/DrugWarningTest.scala
Adding drug warnings data to Drug object
> 1436 drug warning

- src/main/scala/io/opentargets/etl/backend/Disease.scala
Generate indirect Locations using ancestor info
> indirect Locations

- .travis.yml
- project/Dependencies.scala
1.4.0 is compatible with java8
> jgrapht-core compatible version jdk1.8

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Target.scala
The target step is linked to gene_data and reactome data.
Not all the reactome_id are available.
This branch fixes the issue checking if the reactome_id exists in the index (reactome)
> Fix issue with reactome

- .travis.yml
Finally I sorted out this issue
> Token API and file jar created!

- src/main/resources/reference.conf
Prevent them to go beyond 1. Documentation is in line with this scores
> Fix EVA and EVA somatic scores (Clinvar)

- src/main/resources/reference.conf
Adds configuration to rescale the scores
> Add config for crispr datasource

- src/main/resources/reference.conf
> Fix unique_fields

- clickhouse/README
- elasticsearch/load_all.sh
- elasticsearch/load_literature.sh
- elasticsearch/load_openfda_faers.sh
Update readme 
Update elasticsearch script
> update readme and scripts

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/Interactions.scala
Fixed the mapping between interaction_id and the lookup table.
Added the unmatched info
Ref ticket:
https://github.com/opentargets/platform/issues/1539
> Fix interaction mapping

- src/main/scala/io/opentargets/etl/backend/Interactions.scala
> fix distinct

- src/main/scala/io/opentargets/etl/backend/Interactions.scala
Following a conversation with Data Team and David O the interaction is valid when
targetA is null but keep targetB options if null
> Scenario targetA not null

- .gitignore
- scripts/opentargets-disease-meddra-word2vec.sc
- scripts/opentargets-disease-meddra-word2vec.sh
- src/main/scala/io/opentargets/etl/backend/Association.scala
- src/main/scala/io/opentargets/etl/backend/AssociationOTF.scala
- src/main/scala/io/opentargets/etl/backend/Evidence.scala
- src/main/scala/io/opentargets/etl/backend/spark/Helpers.scala
Main changes:
1. compute associations like for like as OTF
2. recover obsolete disease terms from evidence @d0choa
> Mk association cleanning

- README.md
- documentation/etl_current.puml
- documentation/etl_current_full.puml
- documentation/etl_dp_dependencies.puml
- Update readme
- Add component diagram for steps
- Add component diagram for steps and inputs/outputs
> Adding component diagrams of ETL

- src/main/resources/reference.conf
Add orphanet and new info for 21.06
> Config 21.06

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Association.scala
- src/main/scala/io/opentargets/etl/backend/AssociationOTF.scala
Fix issue with disease_data and another glitch.
Change interaction Input file.
> Cm fix association

- src/main/scala/io/opentargets/etl/backend/target/Ensembl.scala
Removed the 'hack' solution to alternative genes which I introduced in 9426eb9de624b074a69b77a55ec2a793cec9814d.
> Refactor alternative gene selection for target.

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/target/GeneOntology.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
resolves opentargets/platform#1037
> Add eco codes to gene ontology on Target

- src/main/scala/io/opentargets/etl/backend/target/Reactome.scala
Relates to opentargets/platform#1678
> Remove `url` field from Target pathways

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
Resolves to opentargets/platform#1699
> Update target orthology: custom sorting

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/EBISearch.scala
- src/test/scala/io/opentargets/etl/backend/EBISearchTest.scala
EBI Search team needs two datasets:
Associations overall direct annotated with approved gene symbol and disease name
and the same info from platform evidence 
Initial JSON format
https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1630
> Ebi search step

- src/main/scala/io/opentargets/etl/backend/target/Target.scala
Fixes bug where paralogs were not assigned the gene symbol of the paralog but of the parent gene.
Resolves to opentargets/platform#1699
> Fix paralog gene symbol on target homolog.

- src/main/resources/reference.conf
Added evidence resource for partner instance
> Add evidence resource for partner

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/OtarProject.scala
- src/test/scala/io/opentargets/etl/backend/OtarProjectTest.scala
Add to the ETL the otar projects info
https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1571
> Add otar project business logic

- configuration/2021/21_09.conf
- src/main/resources/reference.conf
Sorry to be that person, but a change to the name of the data source was made and the configs need to be changed.
Many thanks! @mkarmona
> [Il add biomarkers]

- src/main/scala/io/opentargets/etl/backend/target/Hgnc.scala
- src/test/scala/io/opentargets/etl/backend/target/HgncTest.scala
Resolves opentarget/platform#1738
> 1738 duplicate ensembl ids

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Evidence.scala
- src/main/scala/io/opentargets/etl/backend/spark/IoHelpers.scala
Reverts opentargets/platform-etl-backend#196.
> Revert "1739 add evidence schema"

- src/main/scala/io/opentargets/etl/backend/target/Ncbi.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
- src/main/scala/io/opentargets/etl/backend/target/Uniprot.scala
- src/main/scala/io/opentargets/etl/common/ConsumeWhileIterator.scala
- src/main/scala/io/opentargets/etl/preprocess/uniprot/CommentIdentifiers.scala
- src/main/scala/io/opentargets/etl/preprocess/uniprot/DescriptionIdentifiers.scala
- src/main/scala/io/opentargets/etl/preprocess/uniprot/GeneIdentifiers.scala
- src/main/scala/io/opentargets/etl/preprocess/uniprot/LineIdentifiers.scala
- src/main/scala/io/opentargets/etl/preprocess/uniprot/UniprotConverter.scala
- src/test/resources/uniprot/sample_1.txt
- src/test/resources/uniprot/sample_10.txt
- src/test/scala/io/opentargets/etl/backend/target/UniprotTest.scala
- src/test/scala/io/opentargets/etl/preprocess/UniprotConverterTest.scala
It also cleans the annoying dashes coming from the NCBI file.
> fix: include the symbol from ncbi into the synonyms and the symbol synonyms

- src/main/resources/reference.conf
> Add info for 21.09

- configuration/2021/21_09.conf
- src/main/resources/reference.conf
Added config file and update reference.conf
> 21.09 conf file

- src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala
Many homologues (~30000) do not have a gene symbol. This commit
creates a default of using the gene id. We also do this for human
genes.
Resolves opentargets/platform#1772
> Update Homologue to use gene id as default.

- README.md
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/spark/Helpers.scala
- src/main/scala/io/opentargets/etl/backend/target/GeneWithLocation.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
- src/main/scala/io/opentargets/etl/backend/target/Uniprot.scala
- src/test/resources/target/hpa_sl.tsv
- src/test/resources/uniprot/subcellularLocationUniprot.tsv
- src/test/scala/io/opentargets/etl/backend/target/GeneWithLocationTest.scala
- src/test/scala/io/opentargets/etl/backend/target/UniprotTest.scala
Resolves opentargets/platform#1710
> 1710 add sl locations

- src/main/scala/io/opentargets/etl/backend/AssociationOTF.scala
Relates to opentargets/platform#1751
> 1751 update tractability facet

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/test/scala/io/opentargets/etl/EtlDagTest.scala
Standardised step names as singular.
Alphabetized entries in `Main.scala`
> Update step names in dag

- src/main/resources/reference.conf
Resolves opentargets/platform#1906
> Update chembl scoring to weight studyStopReasonCategories

- configuration/2022/22_02_partner.conf
- src/main/resources/reference.conf
This pull request updates reference.conf with the ot crispr validation config, and also adds the partner preview 22.02 configuration file.
It also contains the weight configuration for ot crispr validation, both in the reference.conf and the partner platform configuration.
> Partner Platform Preview configuration files

- src/main/scala/io/opentargets/etl/backend/target/Uniprot.scala
- src/test/resources/uniprot/sample_1.txt
- src/test/scala/io/opentargets/etl/backend/target/UniprotTest.scala
- src/test/scala/io/opentargets/etl/preprocess/UniprotConverterTest.scala
Resolves opentargets/platform#2587
> Update Target to throw away badly formed location data.

- README.md
- documentation/etl_current.puml
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
Resolves opentargets/platform#1959
> Add OTAR step to ETL DAG.

- src/main/resources/reference.conf
Relates to opentargets/platform#2634
> Remove Encore from configuration.

- src/main/resources/reference.conf
This reverts commit c4d49abd626193f8f8a1ae295acd5bf67bc1e078.
> Revert "Remove Encore from configuration."

- configuration/2022/22_09_ppp.conf
- dataproc/workflow-etl-ppp.sc
- src/main/resources/reference.conf
This PR provides PPP 22.09 release configuration and ETL Dataproc workflow definition.
It also fixes a bug when reading _OTAR Projects_ files that was preventing the pipeline from completing a processing round.
> PPP 22.09 release workflow and OTAR input bug fix

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/OtarProject.scala
Changes in ETL to handle https://github.com/opentargets/issues/issues/2678
- update separator from comma to tab add ppp column to otar projects
- Change otar project PPP column to boolean
- update column name
> Add ppp column otar

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/literature/Processing.scala
- Add sentences config remove un used methods in Processing remove json mapping return sentences df
- update matches
- Add failed matches flag to literature.
- Update reference.conf with proper literature defaults
> Update literature sentence handling

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Epmc.scala
Resolves opentargets/platform#2835
> Add year to epmc evidence

- src/main/resources/reference.conf
see #[2811](https://github.com/opentargets/issues/issues/2811) for context
> feat: add new uncategorised label

- src/main/resources/reference.conf
Updated the file format from tsv to csv
> Update file format to CSV

- src/main/resources/reference.conf
This PR addresses the first task in opentargets/issues#2873
> Enable failed matches in literature

- documentation/etl_current.puml
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/targetEngine/Functions.scala
- src/main/scala/io/opentargets/etl/backend/targetEngine/TargetEngine.scala
- src/main/scala/io/opentargets/etl/backend/targetEngine/UniprotLocationFunctions.scala
- workflow/src/main/resources/reference.conf
- add config settings
- add TargetEngine logic
- add df with single column to merge on update joins add mapping to json
- fix bugs in functions add step to main add select to TargetEngine
- update input path
- sync latest changes from target_engine update documentation remove field
- update source file configuration in reference.conf update workflow config to include TargetEngine job Fix select bug Fix data generation bug remove json mapping
- update membrane logic change targetId column name fix clin trials column
- update membrane function
- update mouse phenotypes path
> rm aotf add target engine

- configuration/2023/23_04_ppp.conf
- src/main/scala/io/opentargets/etl/backend/targetEngine/Functions.scala
- workflow/src/main/resources/reference.conf
- fix hasSecurityEvent calculation add ppp conf file
- fix safetyQuery null issues add steps to public to avoid crashes in public/private
> Fix null values in targetEngine

- documentation/etl_current_full.puml
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/spark/IoHelpers.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
This PR integrates _Target Core Essentiality_ dataset into the ETL _Targets_ output.
> Integration of Target Core Essentiality

- configuration/2023/23_06_platform.conf
- configuration/2023/workflow_23_06.conf
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
- add target essentiality output
- format files
> 2986 target essentiality

- configuration/2023/workflow_23_06.conf
- src/main/scala/io/opentargets/etl/backend/drug/Drug.scala
- src/main/scala/io/opentargets/etl/backend/drug/DrugCommon.scala
- src/main/scala/io/opentargets/etl/backend/drug/DrugWarning.scala
- add isWithdrawn instead of WithdrawnNotice fix drop update description
- update jar version
> 2999 update withdrawn

- configuration/2023/23_06_ppp.conf
- configuration/2023/workflow_ppp_23_06.conf
- workflow/src/main/resources/reference.conf
- workflow/src/test/scala/service/DataprocJobsSpec.scala
- run all steps when processing ppp add pp 23.06 config
- set only ppp steps
> ppp release 23.06

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/literature/Processing.scala
update literature inputs
remove unused config
> update failed locations update literature inputs remove unused config

- documentation/etl_current_full.puml
- src/main/scala/io/opentargets/etl/backend/Expression.scala
This PR includes an update to the PUML diagram for better visualization, and some additional logging messages refactoring.
> PUML layout update

- documentation/etl_current.puml
- documentation/etl_current_full.puml
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/expressions/BaselineExpression.scala
- workflow/src/main/resources/reference.conf
Related to the issue [3024](https://github.com/opentargets/issues/issues/3024)
- Add step BaselineExpression update config to include new step update Configuration
- format BaselineExpression
- add baselineExpression to workflow config add baselineExpression to documentation
- add invalid output BaselineExpression
- fix output reference baselineExpression
- add type annotation to sparkSession
- add logging to step remove invalid output add write-telemitry config write num of invalid outputs to log
- update output file name
> Include baseline expressions

- documentation/etl_current_full.puml
- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/Main.scala
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/Epmc.scala
- src/main/scala/io/opentargets/etl/backend/epmc/Epmc.scala
- src/main/scala/io/opentargets/etl/backend/epmc/EpmcCooccurrences.scala
- update epmc to add cooccurrences
- use correct DF cooccurrences
- refactor Epmc move to folder epmc refactor cooc move to File EpmcCooccurrences refactor uri configured in reference.conf fix output format
- format files
- remove repartitioning of the outputs
- update documentation update output file name
- add logging to EpmcCooccurrences
- format EpmcCooccurrences
- update path
> Include EPMC Cooccurrences

- src/main/resources/reference.conf
This item changes the hpa-sl-ontology input format to parquet
> update tsv input to parquet

- src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala
Please see issue [3285](https://github.com/opentargets/issues/issues/3285) for details and some notebooks showing the reasons for the changes made.
As this fix was only tested locally on a small subset of the literature, when reviewing please do check if everything works as expected on the full dataset.
> Changes made to recover missing literature matches

- src/main/resources/reference.conf
This item updates the map input for expression from json to parquet
> update json map input to parquet

- src/main/resources/reference.conf
Update input format from jsonl to parquet
> 3490 update input format

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala
This PR fixes the problem detailed in https://github.com/opentargets/issues/issues/3482#issuecomment-2444685659 by @remo87.
> Fix homolog load

- src/main/scala/io/opentargets/etl/backend/evidence/Evidence.scala
add formatting to @vivienho changes
> formatted hash variant id

- src/main/resources/reference.conf
This PR fixes some paths that were left incorrect in https://github.com/opentargets/platform-etl-backend/pull/370.
> Fix some paths

- project/Dependencies.scala
Update the spark version so that is aligned to the spark version running in the dataproc cluster as this version supports zstd compression.
> update spark version

- src/main/resources/reference.conf
- src/main/scala/io/opentargets/etl/backend/Configuration.scala
- src/main/scala/io/opentargets/etl/backend/target/Safety.scala
- src/main/scala/io/opentargets/etl/backend/target/Target.scala
- src/test/resources/disease_obsolete_map.jsonl
- src/test/scala/io/opentargets/etl/backend/target/SafetyTest.scala
- workflow/src/main/resources/reference.conf
- **replace obsolete EFOs**
- **fix workflow steps**
- **Move obsolete efo mapping logic and update test**
- **update dependencies**
> 2929 map id

- src/main/resources/reference.conf
This PR closes https://github.com/opentargets/issues/issues/3895
> chore: update clinicalSignificances map to add new classification

- src/main/scala/io/opentargets/etl/backend/pharmacogenomics/Pharmacogenomics.scala
There is a new field in the input data that needs to be added to the final grouping operation
(context https://github.com/opentargets/issues/issues/3876)
> chore(pgx): add `variantAnnotation` to output data

- src/main/scala/io/opentargets/etl/backend/drug/Drug.scala
- src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala
This item solves [3871](https://github.com/opentargets/issues/issues/3871) by replacing the map with a struct
> update map to struct
