src/main/scala/io/opentargets/etl/backend/Target.scala

Added proteinClassification to proteinAnnotations as classes.
Example of behaviour
ENSG00000177000 -> no classes attribute
ENSG00000091831 -> classes attribute
Eg.
```
{
"proteinAnnotations": {
"functions": [
"..."
],
"subcellularLocations": [
"Nucleus",
"Cytoplasm",
"Cell membrane",
"Golgi apparatus"
],
"similarities": [
"Belongs to the nuclear hormone receptor family. NR3 subfamily."
],
"subunits": [
"...."
],
"classes": [
{
"l4": {
"id": 1165,
"label": "Nuclear hormone receptor subfamily 3 group A"
},
"l5": {
"id": 370,
"label": "Nuclear hormone receptor subfamily 3 group A member 1"
},
"l2": {
"id": 1033,
"label": "Nuclear receptor"
},
"l3": {
"id": 1043,
"label": "Nuclear hormone receptor subfamily 3"
},
"l1": {
"id": 12,
"label": "Transcription factor"
}
}
],
"pathways": [],
"id": …
```

added proteinClassification as classes inside proteinAnnotation

---

src/main/resources/reference.conf

replacing variantId by variantRsId as UAF in phewas_catalog

phewas_catalog incorrect unique association field

---

src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala

Updating molecule so that when there exists a synonym but no name, the first synonym is used as the name of the molecule

resolves opentargets/platform#1286 molecules with no name but synonyms

---

src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala
src/test/scala/io/opentargets/etl/backend/Drug/MoleculeTest.scala

Drugs that have not been withdrawn will now have null instead of an
empty struct in the field `withdrawnNotice`

Resolves opentargets/platform#1294

---

src/main/scala/io/opentargets/etl/backend/Interactions.scala

One of the output file was 10GB so we need to reduce the size of the files.
Adding repartitionByRange in order to reduce the size of the files.

Added repartition for interaction evidences

---

build.sbt
src/main/scala/io/opentargets/etl/backend/drug/Indication.scala

Updating join so that efos that are not in the disease index are not
included in the drug dataset. There are approximately 300 indications
removed over 9 EFO ids by this change.

Resolves opentargets/platform#1296

---

README.md
elasticsearch/env.sh
elasticsearch/index_settings.json
elasticsearch/load_drugs.sh
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/Evidence.scala
src/main/scala/io/opentargets/etl/backend/KnownDrugs.scala
src/main/scala/io/opentargets/etl/backend/Search.scala
src/main/scala/io/opentargets/etl/backend/drug/Drug.scala
src/main/scala/io/opentargets/etl/backend/drug/DrugCommon.scala
src/main/scala/io/opentargets/etl/backend/drug/Indication.scala
src/main/scala/io/opentargets/etl/backend/drug/MechanismOfAction.scala
src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala
src/main/scala/io/opentargets/etl/backend/spark/Helpers.scala
src/test/scala/io/opentargets/etl/backend/Drug/IndicationTest.scala
src/test/scala/io/opentargets/etl/backend/Drug/MoleculeTest.scala

Relates to opentargets/plaform#1308. The output name of mechanism_of_action is so that it is compliant with Elasticsearch's index naming rules. 
Also in this PR:
- Fixed deprecated warning on `elasticseach_loader`

Breaking drug step outputs into 'drug', 'mechanism_of_action', and 'indications'

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Evidence.scala

Update scores for `eva` and `eva_somatic` as indicated in opentargets/platform/issues/1319

update clinvar scoring

---

README.md
build.sbt
src/main/scala/io/opentargets/etl/backend/spark/Helpers.scala

Removed native Java calls and replaced with Scala. 
I left some notes in the README explaining why it's necessary to use Java 8.

Removing Java11 methods to run in Dataproc.

---

README.md
src/main/scala/io/opentargets/etl/backend/Interactions.scala

* For intact resource (intact,reactomea and signor) swaps (A, B) and add to the resulset
* String data is symmetrical by definition so no swap is required

Fixed reverse interaction for intact, signor and reactome

---

src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala

Each molecule should have a 'moleculeType' which we rename to
`drugType`. This field is missing for at least one molecule
which breaks the API when it attempts to retrieve the field.

Update Molecule to handle missing 'drugType' values

---

src/main/resources/reference.conf

The score for PhenoDigm is from now on not normalised in the parser when generating the evidence. 
This is an update of the score expression to do this step in the ETL.

Normalize PhenoDigm score

---

src/main/resources/reference.conf

The EVA team submitting updated evidence for the 21.06 release. In this updated dataset there are evidence strings for which the disease terms could not be mapped to EFO. Some of these new disease terms fall into yet unseen clinical significance categories. These categories with the appropriate weights are added to this config file.
Based on the data team stand-up discussion, we came up it the following weights of the new terms.

Adding two new clinical significance terms

---

src/main/scala/io/opentargets/etl/backend/Evidence.scala

Fixes #opentargets/platform/issues/1598

fix: resolve targets function doesnt need to use symbo synonyms

---

README.md
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/spark/IoHelpers.scala
src/test/scala/io/opentargets/etl/ConfigurationTest.scala

I'm tired of accidentally forgetting to delete test output files when developing locally and having test runs fail. My little workaround.

Add write mode configuration to `reference.conf`.

---

README.md
documentation/etl_current.puml
documentation/etl_current_full.puml
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/Main.scala
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/MousePhenotypes.scala
src/main/scala/io/opentargets/etl/backend/target/Hgnc.scala
src/main/scala/io/opentargets/etl/backend/target/Safety.scala

The main purpose of this PR is to deprecate the MousePhenotypes (MP) component of the DP. MP was generated as part of the target step which we want to remove for 21.09. This is a _direct port_ of the logic, and as far as I've been able to test we have actually gone from 11950 MP entries to 13089.
Two mouse genes could not be mapped to Ensembl IDs.
```
+---------------+--------------+-----------------+-----------+
|             id|approvedSymbol|mouse_gene_symbol|human_genes|
+---------------+--------------+-----------------+-----------+
|ENSG00000287542|              |            Herc3|    [HERC3]| < AC issue
|ENSG00000205045|              |            Slfn4|  [SLFN12L]| < AC issue
+---------------+--------------+-----------------+-----------+
```
It looks like both of these failures …

Mouse phenotypes rewrite (data pipeline deprecation)

---

src/main/scala/io/opentargets/etl/backend/target/Ensembl.scala
src/main/scala/io/opentargets/etl/backend/target/GeneOntology.scala

- Fixed logic bug where `alternativeGenes` on non-canonical chromosomes which shared an approved symbol with a canonical gene were not properly grouped
- Gene Ontology (`go`) needs to be mapped to a uniprot `proteinId`. These protein ids are extracted from the Uniprot input, and can be labelled 'uniprot_trembl' or 'uniport_swissprot'. This change ensures we collect all the values we need for the merge.

Target step updates: alternative gene and gene ontology

---

README.md
documentation/etl_current.puml
documentation/etl_current_full.puml
documentation/etl_dp_dependencies.puml
elasticsearch/load_all.sh
elasticsearch/load_go.sh
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/Main.scala
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/Go.scala
src/main/scala/io/opentargets/etl/preprocess/go/GoConverter.scala
src/test/scala/io/opentargets/etl/preprocess/GoConverterTest.scala

Add new index for gene ontology so the FE can query the API for this data instead of an external service. 
The input file is something called `.obo` which is effectively a flat file which doesn't work well with Spark. It's relatively small (results in about 40k records) so can be quickly processed with one pass in native Scala, similar to what is happening with Uniprot. 
I've also alphabetised the entries in `load_all.sh` to make it easier to find things. :)

1547 create gene ontology index

---

src/main/scala/io/opentargets/etl/backend/target/Tractability.scala

Reverting commit 5c710d3. Including false is necessary so we know if the item has been examined with a negative result, or not examined at all.
Resolves opentargets/platform#1672

Add Target tractability 'false' entries.

---

src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala
src/main/scala/io/opentargets/etl/backend/target/Target.scala

- Updated to include low-confidence entries
- Moved linking to `Target.scala` so we can get the approved name for paralogues.
Resolves to opentargets/platform#1699

Update target orthology: low confidence, paralogs.

---

src/main/scala/io/opentargets/etl/backend/target/Target.scala

The data team requested that the arrays either have values, or be nulls rather than the combination of the two.

Replace empty array from target classes with null.

---

elasticsearch/load_drugs.sh

The file uses bash-specific array syntax and crashes with a syntax error
if parsed as a plain POSIX-standard shell script by other shells.

Explicitly run load_drugs.sh with bash

---

src/main/scala/io/opentargets/etl/preprocess/uniprot/DescriptionIdentifiers.scala
src/test/scala/io/opentargets/etl/preprocess/UniprotConverterTest.scala

Resolves opentargets/platform#1695
Some synonyms were being included with too much detail, eg `Putative uncharacterized protein MYH16 {ECO:0000305} ` should be `Putative uncharacterized protein MYH16`. This change removes the details provided in the curly braces.

Update uniprot preprocessing to simplify synonyms.

---

README.md
configuration/2021/21_09.conf
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/Target.scala

Updating `reference.conf` to use current target inputs to facilitate running ETL. 
Creating a new configuration directory so we can start version control of configuration files.

Config refactor

---

src/main/scala/io/opentargets/etl/backend/target/Safety.scala

Parquet does not support columns of `NullType`. We don't have
data yet for `cellId` in target safety as the data team has
not yet produced it. Adding an empty string coerces Spark to
update the type to `StringType`.
When the data becomes available this commit should be reverted.

Fix Target write issue in Parquet format.

---

src/main/resources/reference.conf

Fixing FDA for generating parquet and jsonline output.

fda compatible with parquet/json

---

configuration/2021/21_09.conf
src/main/resources/reference.conf

Cancer biomarkers were previously part of the target annotation.
It is now forming part of the evidence data sources with the name `cancer_genome_interpreter`.
- The new data source has been added to the main config file
- The new data source has been added to the 21.09 config version
- `orphanet`'s config was duplicated in both config files. I've kept the more cramped one.

Add cancer_genome_interpreter to the config file

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/target/Safety.scala
src/main/scala/io/opentargets/etl/backend/target/Target.scala
src/main/scala/io/opentargets/etl/backend/target/Tep.scala
src/test/resources/target/tep_test.json
src/test/scala/io/opentargets/etl/backend/target/TepTest.scala

Updates ETL to use new TEP input file provided by data team.
Updates how `ensemblIdLookupDf` is created and used to make more complicated mappings to ENSG IDs easier. 
Relates to opentargets/platform#1742
Resolves to opentargets/platform#1738

1742 update tep 2

---

README.md
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Evidence.scala
src/main/scala/io/opentargets/etl/backend/spark/IoHelpers.scala

Resolves opentargets/platform#1739
I've built in the functionality where we can use a specific schema on input files. This mechanism didn't solve the problem we were having though of the step failing when there were missing inputs. Not all of the `datasources.unique-fields` in the `reference.conf` file are actually included in the output file (eg. `statisticalTestTail`) so missing input files can still cause the step to fail. 
I've addressed this by checking which of the unique fields in missing and creating those 'fake' columns.

1739 add evidence schema

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/target/Safety.scala

Resolves opentargets/platform#1745
- Updates `Toxcast` to `ToxCast`
- Adds custom events for references 'Force' and 'Lamore' (see commit message for more details)
- Adds description for 'Force', 'Lamore' and 'HeCaTos'
- Updates input files
@cmalangone I've added new input files to `open-targets-pre-data-releases/21.09.1/input/target-inputs/safety` and update `reference.conf`. These input files should never change between releases.

1745 safety data bugs

---

src/main/scala/io/opentargets/etl/backend/Expression.scala

The efo_code is a mandatory field in the GRAPHQL. 
Remove the expressions data without this info
https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1770

fix issue with efo_code

---

src/main/scala/io/opentargets/etl/backend/target/Safety.scala

Update ETL to include target safety 'dosing' when the value is 'general'. We had previously filtered these out. 
Resolves opentargets/platform#1774

Update target safety to include general dosing effects.

---

src/main/scala/io/opentargets/etl/backend/target/GeneWithLocation.scala

Columns `HPA_main`, `HPA_additional`, `HPA_extracellular_location` were
not being dropped. Somewhat surprising behaviour since I would have
thought that the cast to a DS removed unwanted columns.

Remove unwanted columns on Target object.

---

README.md
documentation/etl_current.puml
documentation/etl_current_full.puml
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/Main.scala
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/TargetValidation.scala
src/test/scala/io/opentargets/etl/backend/TargetValidationTest.scala

Target validation step is used for cases when we only want to check that
all the rows in a dataset are also present in the target dataset. In
this way we ensure that ETL outputs link up nicely and we don't have
polluted datasets.
Resolves opentargets/platform#1798

Add target validation step to ETL.

---

configuration/2021/21_09.conf

Modification contains:
* new field for evidence data-sources with id = encore
* defined list of unique association fields.
* score expression describing how the p-value needs to be processed

Adding configuration for the encore evidence set

---

src/main/scala/io/opentargets/etl/preprocess/uniprot/CommentIdentifiers.scala
src/test/scala/io/opentargets/etl/preprocess/UniprotConverterTest.scala

There is a single entry in the Uniprot data which has a non-standard
location form. Because we were splitting on the period character we were
breaking this incorrectly resulting in multiple false entries.
Resolves opentargets/platform#1842

Update Uniprot CommentIdentifiers for non-standard location.

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/ETLSessionContext.scala
src/main/scala/io/opentargets/etl/backend/Evidence.scala

**Only @cmalangone to merge!!**
This was implemented as part of opentargets/platform#1739 but didn't
work in some cases because the `score` method on Associations pulled the
config from the implicit scope. The last fix only implemented
data-source filtering in the `generateHashes` method. 
To prevent having to
repeatedly filter data sources I update the configuration before it is
passed to any ETL step. From the point of view of the ETL the excluded
steps don't exist.

Fix evidence exclusion mechanism

---

src/main/scala/io/opentargets/etl/backend/Reactome.scala

If there are more than one reactome input files in the input directory
both can be ingested creating duplicate entries in the outputs. This
commit ensures that even if that happens the outputs will be clean.
Ideally this should be prevented by specifying the correct inputs in the
configuration file.
Resolves opentargets/platform#1876

Remove risk of duplicate reactome entries.

---

src/main/resources/reference.conf

There's a new version of the Gene2Phenotype dataset, confidence values have changed to accommodate GeneCC consortium. The new scores are reflecting the weights applied for Clingen.
Current counts for each category in the evidence file:
```
+--------------+-----+
|    confidence|count|
+--------------+-----+
|    definitive| 2793|
|both RD and IF|  129|
|        strong|  849|
|       limited|  473|
+--------------+-----+
```
The `moderate` category is added as per source statements: this is future-proofing the datamodel.

Updaing score calculation for gene2phenotype

---

src/main/resources/reference.conf

Remove processing of PheWAS catalog, as this data is no longer part of the evidence dataset.

Remove PheWAS catalog from evidence processing

---

src/main/resources/reference.conf

Changes to the ETL configuration to address 3 upcoming features:
- Extra unique fields are: `ancestryId`, `diseaseFromSource`, `statisticalMethod`, `projectId`. Evidence will be unique already although `projectId` were not included (REGENERON or AZ), because at the moment this field can be inferred from the collapsing model. But I think conceptually it still makes sense to include it so that we bear that in mind and for potential future data sources.
- @mbdebian, please pay extra attention to the p value linearisation. I've set the values by looking at [the definition of pValueLinearRescaling](https://github.com/opentargets/platform-etl-backend/blob/22ff8a6a7361a7192c57280f3814f95bc33f26d5/src/main/scala/io/opentargets/etl/backend/Evidence.scala#L23) and this is the rationale for the …

Il config changes

---

src/main/resources/reference.conf

We’ve implemented a more flexible threshold for the level of statistical significance for the gene_burden evidence set (see more here https://github.com/opentargets/evidence_datasource_parsers/pull/121#commitcomment-70971329)
Therefore we want to lower the p values once they are linearised so that these less significant evidence score lower.

Update gene_burden linearisation

---

src/main/scala/io/opentargets/etl/Main.scala
src/test/scala/io/opentargets/etl/EtlTest.scala

When steps are included as part of a workflow we want to break when an
unknown step is called rather than success but with no output or warning
.

Update step execution to fail when step is unknown.

---

src/main/scala/io/opentargets/etl/backend/target/Ensembl.scala
src/test/scala/io/opentargets/etl/backend/target/EnsemblTest.scala

In the 22.09 release there were ~40 duplicate targets introduced. This
was because genecode assigned some transcripts to two separate genes.
This filter ensures that the canonical transcript is only applied to to
the Ensembl target and does not introduce a shadow duplicate.
Resolves opentargets/platform#2732

Ensure no duplicate targets are introduced by canonical transcripts.

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/spark/IoHelpers.scala
src/main/scala/io/opentargets/etl/backend/spark/MetadataHelper.scala
src/test/scala/io/opentargets/etl/backend/spark/MetadataHelperSpec.scala

Updates metadata generation so that all outputs are provided with
metadata.
Metadata is now saved in the directory
`common.output-base-path`/metadata . Metadata for each dataset is
appended to this directory, so if we run the pipeline multiple times in
the same place without cleaning up after ourselves we potentially will
have multiple metadata files for the same input.
Resolves opentargets/platform#2780

Update Metadata generation.

---

build.sbt
configuration/2022/22_11_platform.conf
configuration/2022/22_11_ppp.conf
project/Dependencies.scala
src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/Main.scala
src/main/scala/io/opentargets/etl/backend/OtarProject.scala
src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala
src/main/scala/io/opentargets/etl/backend/literature/Literature.scala
src/main/scala/io/opentargets/etl/backend/literature/PreProcessing.scala
src/main/scala/io/opentargets/etl/backend/literature/Processing.scala
src/test/scala/io/opentargets/etl/backend/OtarProjectTest.scala
workflow/src/main/resources/reference.conf
workflow/src/main/scala/io/opentargets/workflow/model/Configuration.scala
workflow/src/main/scala/io/opentargets/workflow/service/DataprocCluster.scala
workflow/src/main/scala/io/opentargets/workflow/service/DataprocJobs.scala
workflow/src/test/scala/service/DataprocClusterSpec.scala

Lots of small changes that came about because of the release, as well as the
usual addition of configuration files.
Changes:
- Some refactoring in Literature to make the names easier to understand
- Update the workflow to accept zero workers
- Update workflow to parameterise disk configuration
- Update FDA path in Main so that it short-circuits on pre-existing outputs
- Update OTAR to use the new data format. 
- Add configuration files (platform and PPP)

2211 release fixes

---

src/main/scala/io/opentargets/etl/backend/literature/Processing.scala

This PR changes _pmid_ type for ETL outputs from _Long_ to _String_

Bug fix literature index, 'pmid' as String

---

src/main/resources/reference.conf

For the 23.06 Platform release a new evidence source is introduced: `crispr_screen`. The PR adds the logic to generate score.

Adding recipe to ingest crispr_screen evidence

---

src/main/scala/io/opentargets/etl/backend/drug/MechanismOfAction.scala

The Mechanism of Action table has irrelevant information that the data team will try to remodel in the future with ChEMBL. For the time being, this PR includes changes to the way the ETL processes the MoA data that were raised by [#3005](https://github.com/opentargets/issues/issues/3005):
- Switch the filtering condition from"OR"s to "AND"s, so that if any of the clauses is not met, that row is filtered out. After inspecting the data, the conditions are:
- Rows with null in `mechanismOfAction` are filtered out;
- Rows where `targets` is null or an empty array are discarded;
- Rows where `chemblIds` is null or an empty array are discarded;
Having a healthy MoA table will close [#3005](https://github.com/opentargets/issues/issues/3005)

Filter out incomplete data for a drug mechanism of action

---

src/main/scala/io/opentargets/etl/backend/evidence/DirectionOfEffect.scala

This pr solves [3221](https://github.com/opentargets/issues/issues/3221)
It modifies the cast from float to double due to the number of decimals in the fields

update casting in direction of effect

---

src/main/scala/io/opentargets/etl/common/DrugUtils.scala

This PR solves the data bug for the item [3116](https://github.com/opentargets/issues/issues/3116).
Some of the values of the datasourceVersion were wrong and causing the data ingestion to fail. The cause of the bug was the union logic that wasn't properly done.

update union to unionByName

---

src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala

The raw data can have `Unknown` as drug type. After coalescing, this field can have `unknown` or `Unknown` as reported by an user here https://github.com/opentargets/issues/issues/3354 
This should fix the problem, but please double check that the Scala syntax is correct.

fix(molecule): harmonise null drug types

---

src/main/resources/reference.conf

This datasource reports variation with rsIDs.
We are postprocessing it to add the variantId. Because rsIDs are ambiguous, this addition causes an explosion in the data, meaning that there will be multiple evidence strings reporting the same disease and rsId.
To avoid them being marked as duplicates, we should add `variantId` as an unique field

feat(uniprot_variants): add `variantId` as an unique field

---

src/main/resources/reference.conf

Same to https://github.com/opentargets/platform-etl-backend/pull/349 but using the release branch as the base branch
This datasource reports variation with rsIDs.
We are postprocessing it to add the variantId. Because rsIDs are ambiguous, this addition causes an explosion in the data, meaning that there will be multiple evidence strings reporting the same disease and rsId.
To avoid them being marked as duplicates, we should add variantId as an unique field

Il uniprot add variant unique

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/Main.scala
src/main/scala/io/opentargets/etl/backend/Configuration.scala
src/main/scala/io/opentargets/etl/backend/so/SequenceOntology.scala
workflow/src/main/resources/reference.conf

Add new SO step to the ETL to map the sequence ontology inputs and solve item [3499](https://github.com/opentargets/issues/issues/3499)
- **Add Sequence Ontology Add so Configuration Add basic props mapping Add synonyms mappings Add definition mapping**
- **add logging**
- **refactor to extract logic to methods**
- **leave only fields used by the API**

3499 sequence ontology

---

src/main/scala/io/opentargets/etl/backend/evidence/Evidence.scala

This PR adds a function for hashing long variant Ids into the evidence step of the platform ETL.

feat: add function for hashing long variant ids

---

src/main/scala/io/opentargets/etl/backend/target/Target.scala

Gentropy uses a `gene_index` which contains a subset of columns from the target index in the platform etl, plus an additional `tss` column.  As the gentropy pipelines will now use the target index directly, we should add the `tss` column to the target index.
This PR adds the `tss` column to the target index.

feat: add tss column to target index

---

src/main/scala/io/opentargets/etl/backend/target/Target.scala

See PR #369 
Values of `canonicalTranscript.strand` should be "+" and "-", not 1 and -1

fix: change values of strand in the addTss function

---

src/main/resources/reference.conf
src/main/scala/io/opentargets/etl/backend/evidence/DirectionOfEffect.scala

As the issue [#3715](https://github.com/opentargets/issues/issues/3715) explains, we are dropping `ot_genetics` evidence. This includes:

chore: removing references to ot_genetics from configuration and etl
